// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cordic_base (
        ap_clk,
        ap_rst,
        inputData_in_V_read,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [47:0] inputData_in_V_read;
output  [24:0] ap_return;
input   ap_ce;

wire   [0:0] tmp_1160_fu_156_p1;
reg   [0:0] tmp_1160_reg_2446;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_flag00011001;
reg   [0:0] ap_reg_pp0_iter1_tmp_1160_reg_2446;
reg   [0:0] ap_reg_pp0_iter2_tmp_1160_reg_2446;
reg   [0:0] ap_reg_pp0_iter3_tmp_1160_reg_2446;
wire   [4:0] sqrt_int_2_4_v_fu_556_p3;
reg   [4:0] sqrt_int_2_4_v_reg_2451;
wire   [0:0] tmp_1178_fu_626_p3;
reg   [0:0] tmp_1178_reg_2457;
wire   [49:0] p_Result_29_6_fu_664_p5;
reg   [49:0] p_Result_29_6_reg_2462;
reg   [1:0] tmp_30_reg_2468;
reg   [1:0] tmp_35_reg_2473;
reg   [1:0] tmp_40_reg_2478;
reg   [1:0] tmp_45_reg_2483;
reg   [1:0] tmp_50_reg_2488;
reg   [1:0] tmp_55_reg_2493;
reg   [1:0] tmp_60_reg_2498;
reg   [1:0] ap_reg_pp0_iter1_tmp_60_reg_2498;
reg   [1:0] tmp_65_reg_2503;
reg   [1:0] ap_reg_pp0_iter1_tmp_65_reg_2503;
reg   [1:0] ap_reg_pp0_iter2_tmp_65_reg_2503;
reg   [1:0] tmp_70_reg_2508;
reg   [1:0] ap_reg_pp0_iter1_tmp_70_reg_2508;
reg   [1:0] ap_reg_pp0_iter2_tmp_70_reg_2508;
reg   [1:0] tmp_75_reg_2513;
reg   [1:0] ap_reg_pp0_iter1_tmp_75_reg_2513;
reg   [1:0] ap_reg_pp0_iter2_tmp_75_reg_2513;
reg   [1:0] tmp_80_reg_2518;
reg   [1:0] ap_reg_pp0_iter1_tmp_80_reg_2518;
reg   [1:0] ap_reg_pp0_iter2_tmp_80_reg_2518;
reg   [1:0] tmp_85_reg_2523;
reg   [1:0] ap_reg_pp0_iter1_tmp_85_reg_2523;
reg   [1:0] ap_reg_pp0_iter2_tmp_85_reg_2523;
reg   [1:0] tmp_90_reg_2528;
reg   [1:0] ap_reg_pp0_iter1_tmp_90_reg_2528;
reg   [1:0] ap_reg_pp0_iter2_tmp_90_reg_2528;
reg   [1:0] tmp_95_reg_2533;
reg   [1:0] ap_reg_pp0_iter1_tmp_95_reg_2533;
reg   [1:0] ap_reg_pp0_iter2_tmp_95_reg_2533;
reg   [1:0] ap_reg_pp0_iter3_tmp_95_reg_2533;
reg   [1:0] tmp_100_reg_2538;
reg   [1:0] ap_reg_pp0_iter1_tmp_100_reg_2538;
reg   [1:0] ap_reg_pp0_iter2_tmp_100_reg_2538;
reg   [1:0] ap_reg_pp0_iter3_tmp_100_reg_2538;
reg   [1:0] tmp_105_reg_2543;
reg   [1:0] ap_reg_pp0_iter1_tmp_105_reg_2543;
reg   [1:0] ap_reg_pp0_iter2_tmp_105_reg_2543;
reg   [1:0] ap_reg_pp0_iter3_tmp_105_reg_2543;
reg   [1:0] tmp_110_reg_2548;
reg   [1:0] ap_reg_pp0_iter1_tmp_110_reg_2548;
reg   [1:0] ap_reg_pp0_iter2_tmp_110_reg_2548;
reg   [1:0] ap_reg_pp0_iter3_tmp_110_reg_2548;
wire   [24:0] sqrt_int_2_1_fu_1344_p3;
reg   [24:0] sqrt_int_2_1_reg_2553;
reg   [24:0] ap_reg_pp0_iter2_sqrt_int_2_1_reg_2553;
wire   [49:0] p_Result_29_11_fu_1371_p5;
reg   [49:0] p_Result_29_11_reg_2559;
wire   [22:0] tmp_1211_fu_1383_p1;
reg   [22:0] tmp_1211_reg_2565;
wire   [0:0] tmp_1214_fu_1401_p3;
reg   [0:0] tmp_1214_reg_2570;
wire   [49:0] p_Result_29_12_fu_1427_p5;
reg   [49:0] p_Result_29_12_reg_2575;
wire   [24:0] sqrt_int_2_13_fu_1931_p3;
reg   [24:0] sqrt_int_2_13_reg_2581;
wire   [49:0] p_Result_29_18_fu_1958_p5;
reg   [49:0] p_Result_29_18_reg_2587;
wire   [22:0] tmp_1246_fu_1970_p1;
reg   [22:0] tmp_1246_reg_2593;
wire    ap_block_pp0_stage0_flag00000000;
wire   [0:0] tmp_fu_148_p3;
wire   [49:0] p_Result_2_fu_160_p3;
wire   [49:0] rem_next_V_fu_168_p2;
wire   [0:0] tmp_1161_fu_174_p3;
wire   [49:0] p_Result_29_0_rem_s_fu_188_p3;
wire   [23:0] tmp_1162_fu_196_p1;
wire   [1:0] tmp_1_fu_200_p4;
wire   [25:0] tmp_2_fu_210_p3;
wire   [0:0] not_Result_3_fu_182_p2;
wire   [22:0] tmp_3_fu_230_p1;
wire   [49:0] p_Result_29_1_fu_218_p5;
wire   [49:0] p_Result_30_1_s_fu_234_p4;
wire   [49:0] rem_next_V_1_fu_244_p2;
wire   [0:0] tmp_1163_fu_258_p3;
wire   [1:0] tmp_4_fu_250_p3;
wire   [1:0] tmp_118_fu_266_p3;
wire   [49:0] p_0289_2_i_1_fu_282_p3;
wire   [23:0] tmp_1164_fu_290_p1;
wire   [1:0] tmp_7_fu_294_p4;
wire   [25:0] tmp_8_fu_304_p3;
wire   [1:0] sqrt_int_2_1_v_fu_274_p3;
wire   [22:0] tmp_9_fu_324_p1;
wire   [49:0] p_Result_29_2_fu_312_p5;
wire   [49:0] p_Result_30_2_s_fu_328_p4;
wire   [49:0] rem_next_V_2_fu_338_p2;
wire   [0:0] tmp_1165_fu_352_p3;
wire   [2:0] tmp_s_fu_344_p3;
wire   [2:0] tmp_584_fu_360_p3;
wire   [49:0] p_0289_2_i_2_fu_376_p3;
wire   [23:0] tmp_1166_fu_384_p1;
wire   [1:0] tmp_10_fu_388_p4;
wire   [25:0] tmp_11_fu_398_p3;
wire   [2:0] sqrt_int_2_2_v_fu_368_p3;
wire   [22:0] tmp_12_fu_418_p1;
wire   [49:0] p_Result_29_3_fu_406_p5;
wire   [49:0] p_Result_30_3_s_fu_422_p4;
wire   [49:0] rem_next_V_3_fu_432_p2;
wire   [0:0] tmp_1168_fu_446_p3;
wire   [3:0] tmp_1167_fu_438_p3;
wire   [3:0] tmp_1169_fu_454_p3;
wire   [49:0] p_0289_2_i_3_fu_470_p3;
wire   [23:0] tmp_1170_fu_478_p1;
wire   [1:0] tmp_15_fu_482_p4;
wire   [25:0] tmp_16_fu_492_p3;
wire   [3:0] sqrt_int_2_3_v_fu_462_p3;
wire   [22:0] tmp_17_fu_512_p1;
wire   [49:0] p_Result_29_4_fu_500_p5;
wire   [49:0] p_Result_30_4_s_fu_516_p4;
wire   [49:0] rem_next_V_4_fu_526_p2;
wire   [0:0] tmp_1172_fu_540_p3;
wire   [4:0] tmp_1171_fu_532_p3;
wire   [4:0] tmp_1173_fu_548_p3;
wire   [49:0] p_0289_2_i_4_fu_564_p3;
wire   [23:0] tmp_1174_fu_572_p1;
wire   [1:0] tmp_20_fu_576_p4;
wire   [25:0] tmp_21_fu_586_p3;
wire   [22:0] tmp_1175_fu_606_p1;
wire   [49:0] p_Result_29_5_fu_594_p5;
wire   [49:0] p_Result_30_5_s_fu_610_p4;
wire   [49:0] rem_next_V_5_fu_620_p2;
wire   [49:0] p_0289_2_i_5_fu_634_p3;
wire   [23:0] tmp_1180_fu_642_p1;
wire   [1:0] tmp_25_fu_646_p4;
wire   [25:0] tmp_26_fu_656_p3;
wire   [5:0] tmp_1176_fu_846_p3;
wire   [5:0] tmp_1179_fu_857_p3;
wire   [24:0] tmp_1177_fu_853_p1;
wire   [24:0] p_Result_33_5_fu_864_p1;
wire   [24:0] sqrt_int_2_5_fu_868_p3;
wire   [22:0] tmp_1181_fu_875_p1;
wire   [49:0] p_Result_30_6_s_fu_879_p4;
wire   [49:0] rem_next_V_6_fu_889_p2;
wire   [23:0] tmp_1182_fu_894_p1;
wire   [0:0] tmp_1184_fu_904_p3;
wire   [24:0] tmp_1183_fu_898_p2;
wire   [24:0] p_Result_33_6_fu_912_p3;
wire   [49:0] p_0289_2_i_6_fu_928_p3;
wire   [23:0] tmp_1185_fu_935_p1;
wire   [25:0] tmp_31_fu_939_p3;
wire   [24:0] sqrt_int_2_6_fu_920_p3;
wire   [22:0] tmp_1186_fu_958_p1;
wire   [49:0] p_Result_29_7_fu_946_p5;
wire   [49:0] p_Result_30_7_s_fu_962_p4;
wire   [49:0] rem_next_V_7_fu_972_p2;
wire   [23:0] tmp_1187_fu_978_p1;
wire   [0:0] tmp_1189_fu_988_p3;
wire   [24:0] tmp_1188_fu_982_p2;
wire   [24:0] p_Result_33_7_fu_996_p3;
wire   [49:0] p_0289_2_i_7_fu_1012_p3;
wire   [23:0] tmp_1190_fu_1020_p1;
wire   [25:0] tmp_36_fu_1024_p3;
wire   [24:0] sqrt_int_2_7_fu_1004_p3;
wire   [22:0] tmp_1191_fu_1043_p1;
wire   [49:0] p_Result_29_8_fu_1031_p5;
wire   [49:0] p_Result_30_8_s_fu_1047_p4;
wire   [49:0] rem_next_V_8_fu_1057_p2;
wire   [23:0] tmp_1192_fu_1063_p1;
wire   [0:0] tmp_1194_fu_1073_p3;
wire   [24:0] tmp_1193_fu_1067_p2;
wire   [24:0] p_Result_33_8_fu_1081_p3;
wire   [49:0] p_0289_2_i_8_fu_1097_p3;
wire   [23:0] tmp_1195_fu_1105_p1;
wire   [25:0] tmp_41_fu_1109_p3;
wire   [24:0] sqrt_int_2_8_fu_1089_p3;
wire   [22:0] tmp_1196_fu_1128_p1;
wire   [49:0] p_Result_29_9_fu_1116_p5;
wire   [49:0] p_Result_30_9_s_fu_1132_p4;
wire   [49:0] rem_next_V_9_fu_1142_p2;
wire   [23:0] tmp_1197_fu_1148_p1;
wire   [0:0] tmp_1199_fu_1158_p3;
wire   [24:0] tmp_1198_fu_1152_p2;
wire   [24:0] p_Result_33_9_fu_1166_p3;
wire   [49:0] p_0289_2_i_9_fu_1182_p3;
wire   [23:0] tmp_1200_fu_1190_p1;
wire   [25:0] tmp_46_fu_1194_p3;
wire   [24:0] sqrt_int_2_9_fu_1174_p3;
wire   [22:0] tmp_1201_fu_1213_p1;
wire   [49:0] p_Result_29_s_fu_1201_p5;
wire   [49:0] p_Result_30_10_s_fu_1217_p4;
wire   [49:0] rem_next_V_s_fu_1227_p2;
wire   [23:0] tmp_1202_fu_1233_p1;
wire   [0:0] tmp_1204_fu_1243_p3;
wire   [24:0] tmp_1203_fu_1237_p2;
wire   [24:0] p_Result_33_s_fu_1251_p3;
wire   [49:0] p_0289_2_i_s_fu_1267_p3;
wire   [23:0] tmp_1205_fu_1275_p1;
wire   [25:0] tmp_51_fu_1279_p3;
wire   [24:0] sqrt_int_2_s_fu_1259_p3;
wire   [22:0] tmp_1206_fu_1298_p1;
wire   [49:0] p_Result_29_10_fu_1286_p5;
wire   [49:0] p_Result_30_11_s_fu_1302_p4;
wire   [49:0] rem_next_V_10_fu_1312_p2;
wire   [23:0] tmp_1207_fu_1318_p1;
wire   [0:0] tmp_1209_fu_1328_p3;
wire   [24:0] tmp_1208_fu_1322_p2;
wire   [24:0] p_Result_33_1_fu_1336_p3;
wire   [49:0] p_0289_2_i_10_fu_1352_p3;
wire   [23:0] tmp_1210_fu_1360_p1;
wire   [25:0] tmp_56_fu_1364_p3;
wire   [49:0] p_Result_30_12_s_fu_1387_p4;
wire   [49:0] rem_next_V_11_fu_1396_p2;
wire   [49:0] p_0289_2_i_11_fu_1409_p3;
wire   [23:0] tmp_1215_fu_1416_p1;
wire   [25:0] tmp_61_fu_1420_p3;
wire   [23:0] tmp_1212_fu_1439_p1;
wire   [24:0] tmp_1213_fu_1442_p2;
wire   [24:0] p_Result_33_2_fu_1447_p3;
wire   [24:0] sqrt_int_2_2_fu_1455_p3;
wire   [22:0] tmp_1216_fu_1462_p1;
wire   [49:0] p_Result_30_13_s_fu_1466_p4;
wire   [49:0] rem_next_V_12_fu_1476_p2;
wire   [23:0] tmp_1217_fu_1481_p1;
wire   [0:0] tmp_1219_fu_1491_p3;
wire   [24:0] tmp_1218_fu_1485_p2;
wire   [24:0] p_Result_33_3_fu_1499_p3;
wire   [49:0] p_0289_2_i_12_fu_1515_p3;
wire   [23:0] tmp_1220_fu_1522_p1;
wire   [25:0] tmp_66_fu_1526_p3;
wire   [24:0] sqrt_int_2_3_fu_1507_p3;
wire   [22:0] tmp_1221_fu_1545_p1;
wire   [49:0] p_Result_29_13_fu_1533_p5;
wire   [49:0] p_Result_30_14_s_fu_1549_p4;
wire   [49:0] rem_next_V_13_fu_1559_p2;
wire   [23:0] tmp_1222_fu_1565_p1;
wire   [0:0] tmp_1224_fu_1575_p3;
wire   [24:0] tmp_1223_fu_1569_p2;
wire   [24:0] p_Result_33_4_fu_1583_p3;
wire   [49:0] p_0289_2_i_13_fu_1599_p3;
wire   [23:0] tmp_1225_fu_1607_p1;
wire   [25:0] tmp_71_fu_1611_p3;
wire   [24:0] sqrt_int_2_4_fu_1591_p3;
wire   [22:0] tmp_1226_fu_1630_p1;
wire   [49:0] p_Result_29_14_fu_1618_p5;
wire   [49:0] p_Result_30_15_s_fu_1634_p4;
wire   [49:0] rem_next_V_14_fu_1644_p2;
wire   [23:0] tmp_1227_fu_1650_p1;
wire   [0:0] tmp_1229_fu_1660_p3;
wire   [24:0] tmp_1228_fu_1654_p2;
wire   [24:0] p_Result_33_10_fu_1668_p3;
wire   [49:0] p_0289_2_i_14_fu_1684_p3;
wire   [23:0] tmp_1230_fu_1692_p1;
wire   [25:0] tmp_76_fu_1696_p3;
wire   [24:0] sqrt_int_2_10_fu_1676_p3;
wire   [22:0] tmp_1231_fu_1715_p1;
wire   [49:0] p_Result_29_15_fu_1703_p5;
wire   [49:0] p_Result_30_16_s_fu_1719_p4;
wire   [49:0] rem_next_V_15_fu_1729_p2;
wire   [23:0] tmp_1232_fu_1735_p1;
wire   [0:0] tmp_1234_fu_1745_p3;
wire   [24:0] tmp_1233_fu_1739_p2;
wire   [24:0] p_Result_33_11_fu_1753_p3;
wire   [49:0] p_0289_2_i_15_fu_1769_p3;
wire   [23:0] tmp_1235_fu_1777_p1;
wire   [25:0] tmp_81_fu_1781_p3;
wire   [24:0] sqrt_int_2_11_fu_1761_p3;
wire   [22:0] tmp_1236_fu_1800_p1;
wire   [49:0] p_Result_29_16_fu_1788_p5;
wire   [49:0] p_Result_30_17_s_fu_1804_p4;
wire   [49:0] rem_next_V_16_fu_1814_p2;
wire   [23:0] tmp_1237_fu_1820_p1;
wire   [0:0] tmp_1239_fu_1830_p3;
wire   [24:0] tmp_1238_fu_1824_p2;
wire   [24:0] p_Result_33_12_fu_1838_p3;
wire   [49:0] p_0289_2_i_16_fu_1854_p3;
wire   [23:0] tmp_1240_fu_1862_p1;
wire   [25:0] tmp_86_fu_1866_p3;
wire   [24:0] sqrt_int_2_12_fu_1846_p3;
wire   [22:0] tmp_1241_fu_1885_p1;
wire   [49:0] p_Result_29_17_fu_1873_p5;
wire   [49:0] p_Result_30_18_s_fu_1889_p4;
wire   [49:0] rem_next_V_17_fu_1899_p2;
wire   [23:0] tmp_1242_fu_1905_p1;
wire   [0:0] tmp_1244_fu_1915_p3;
wire   [24:0] tmp_1243_fu_1909_p2;
wire   [24:0] p_Result_33_13_fu_1923_p3;
wire   [49:0] p_0289_2_i_17_fu_1939_p3;
wire   [23:0] tmp_1245_fu_1947_p1;
wire   [25:0] tmp_91_fu_1951_p3;
wire   [49:0] p_Result_30_19_s_fu_1974_p4;
wire   [49:0] rem_next_V_18_fu_1983_p2;
wire   [23:0] tmp_1247_fu_1988_p1;
wire   [0:0] tmp_1249_fu_1996_p3;
wire   [24:0] tmp_1248_fu_1991_p2;
wire   [24:0] p_Result_33_14_fu_2004_p3;
wire   [49:0] p_0289_2_i_18_fu_2020_p3;
wire   [23:0] tmp_1250_fu_2027_p1;
wire   [25:0] tmp_96_fu_2031_p3;
wire   [24:0] sqrt_int_2_14_fu_2012_p3;
wire   [22:0] tmp_1251_fu_2050_p1;
wire   [49:0] p_Result_29_19_fu_2038_p5;
wire   [49:0] p_Result_30_20_s_fu_2054_p4;
wire   [49:0] rem_next_V_19_fu_2064_p2;
wire   [23:0] tmp_1252_fu_2070_p1;
wire   [0:0] tmp_1254_fu_2080_p3;
wire   [24:0] tmp_1253_fu_2074_p2;
wire   [24:0] p_Result_33_15_fu_2088_p3;
wire   [49:0] p_0289_2_i_19_fu_2104_p3;
wire   [23:0] tmp_1255_fu_2112_p1;
wire   [25:0] tmp_101_fu_2116_p3;
wire   [24:0] sqrt_int_2_15_fu_2096_p3;
wire   [22:0] tmp_1256_fu_2135_p1;
wire   [49:0] p_Result_29_20_fu_2123_p5;
wire   [49:0] p_Result_30_21_s_fu_2139_p4;
wire   [49:0] rem_next_V_20_fu_2149_p2;
wire   [23:0] tmp_1257_fu_2155_p1;
wire   [0:0] tmp_1259_fu_2165_p3;
wire   [24:0] tmp_1258_fu_2159_p2;
wire   [24:0] p_Result_33_16_fu_2173_p3;
wire   [49:0] p_0289_2_i_20_fu_2189_p3;
wire   [23:0] tmp_1260_fu_2197_p1;
wire   [25:0] tmp_106_fu_2201_p3;
wire   [24:0] sqrt_int_2_16_fu_2181_p3;
wire   [22:0] tmp_1261_fu_2220_p1;
wire   [49:0] p_Result_29_21_fu_2208_p5;
wire   [49:0] p_Result_30_22_s_fu_2224_p4;
wire   [49:0] rem_next_V_21_fu_2234_p2;
wire   [23:0] tmp_1262_fu_2240_p1;
wire   [0:0] tmp_1264_fu_2250_p3;
wire   [24:0] tmp_1263_fu_2244_p2;
wire   [24:0] p_Result_33_17_fu_2258_p3;
wire   [49:0] p_0289_2_i_21_fu_2274_p3;
wire   [23:0] tmp_1265_fu_2282_p1;
wire   [25:0] tmp_111_fu_2286_p3;
wire   [24:0] sqrt_int_2_17_fu_2266_p3;
wire   [22:0] tmp_1266_fu_2305_p1;
wire   [49:0] p_Result_29_22_fu_2293_p5;
wire   [49:0] p_Result_30_23_s_fu_2309_p4;
wire   [49:0] rem_next_V_22_fu_2319_p2;
wire   [23:0] tmp_1267_fu_2325_p1;
wire   [0:0] tmp_1269_fu_2335_p3;
wire   [24:0] tmp_1268_fu_2329_p2;
wire   [24:0] p_Result_33_18_fu_2343_p3;
wire   [49:0] p_0289_2_i_22_fu_2359_p3;
wire   [23:0] tmp_1270_fu_2367_p1;
wire   [25:0] tmp_115_fu_2371_p4;
wire   [24:0] sqrt_int_2_18_fu_2351_p3;
wire   [22:0] tmp_1271_fu_2392_p1;
wire   [49:0] p_Result_29_23_fu_2380_p5;
wire   [49:0] p_Result_30_24_s_fu_2396_p4;
wire   [49:0] rem_next_V_23_fu_2406_p2;
wire   [23:0] tmp_1272_fu_2412_p1;
wire   [0:0] tmp_1274_fu_2422_p3;
wire   [24:0] tmp_1273_fu_2416_p2;
wire   [24:0] p_Result_33_19_fu_2430_p3;

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (ap_ce == 1'b1))) begin
        ap_reg_pp0_iter1_tmp_100_reg_2538 <= tmp_100_reg_2538;
        ap_reg_pp0_iter1_tmp_105_reg_2543 <= tmp_105_reg_2543;
        ap_reg_pp0_iter1_tmp_110_reg_2548 <= tmp_110_reg_2548;
        ap_reg_pp0_iter1_tmp_1160_reg_2446 <= tmp_1160_reg_2446;
        ap_reg_pp0_iter1_tmp_60_reg_2498 <= tmp_60_reg_2498;
        ap_reg_pp0_iter1_tmp_65_reg_2503 <= tmp_65_reg_2503;
        ap_reg_pp0_iter1_tmp_70_reg_2508 <= tmp_70_reg_2508;
        ap_reg_pp0_iter1_tmp_75_reg_2513 <= tmp_75_reg_2513;
        ap_reg_pp0_iter1_tmp_80_reg_2518 <= tmp_80_reg_2518;
        ap_reg_pp0_iter1_tmp_85_reg_2523 <= tmp_85_reg_2523;
        ap_reg_pp0_iter1_tmp_90_reg_2528 <= tmp_90_reg_2528;
        ap_reg_pp0_iter1_tmp_95_reg_2533 <= tmp_95_reg_2533;
        ap_reg_pp0_iter2_sqrt_int_2_1_reg_2553[11 : 0] <= sqrt_int_2_1_reg_2553[11 : 0];
        ap_reg_pp0_iter2_tmp_100_reg_2538 <= ap_reg_pp0_iter1_tmp_100_reg_2538;
        ap_reg_pp0_iter2_tmp_105_reg_2543 <= ap_reg_pp0_iter1_tmp_105_reg_2543;
        ap_reg_pp0_iter2_tmp_110_reg_2548 <= ap_reg_pp0_iter1_tmp_110_reg_2548;
        ap_reg_pp0_iter2_tmp_1160_reg_2446 <= ap_reg_pp0_iter1_tmp_1160_reg_2446;
        ap_reg_pp0_iter2_tmp_65_reg_2503 <= ap_reg_pp0_iter1_tmp_65_reg_2503;
        ap_reg_pp0_iter2_tmp_70_reg_2508 <= ap_reg_pp0_iter1_tmp_70_reg_2508;
        ap_reg_pp0_iter2_tmp_75_reg_2513 <= ap_reg_pp0_iter1_tmp_75_reg_2513;
        ap_reg_pp0_iter2_tmp_80_reg_2518 <= ap_reg_pp0_iter1_tmp_80_reg_2518;
        ap_reg_pp0_iter2_tmp_85_reg_2523 <= ap_reg_pp0_iter1_tmp_85_reg_2523;
        ap_reg_pp0_iter2_tmp_90_reg_2528 <= ap_reg_pp0_iter1_tmp_90_reg_2528;
        ap_reg_pp0_iter2_tmp_95_reg_2533 <= ap_reg_pp0_iter1_tmp_95_reg_2533;
        ap_reg_pp0_iter3_tmp_100_reg_2538 <= ap_reg_pp0_iter2_tmp_100_reg_2538;
        ap_reg_pp0_iter3_tmp_105_reg_2543 <= ap_reg_pp0_iter2_tmp_105_reg_2543;
        ap_reg_pp0_iter3_tmp_110_reg_2548 <= ap_reg_pp0_iter2_tmp_110_reg_2548;
        ap_reg_pp0_iter3_tmp_1160_reg_2446 <= ap_reg_pp0_iter2_tmp_1160_reg_2446;
        ap_reg_pp0_iter3_tmp_95_reg_2533 <= ap_reg_pp0_iter2_tmp_95_reg_2533;
        p_Result_29_11_reg_2559 <= p_Result_29_11_fu_1371_p5;
        p_Result_29_12_reg_2575 <= p_Result_29_12_fu_1427_p5;
        p_Result_29_18_reg_2587 <= p_Result_29_18_fu_1958_p5;
        p_Result_29_6_reg_2462 <= p_Result_29_6_fu_664_p5;
        sqrt_int_2_13_reg_2581[18 : 0] <= sqrt_int_2_13_fu_1931_p3[18 : 0];
        sqrt_int_2_1_reg_2553[11 : 0] <= sqrt_int_2_1_fu_1344_p3[11 : 0];
        sqrt_int_2_4_v_reg_2451 <= sqrt_int_2_4_v_fu_556_p3;
        tmp_100_reg_2538 <= {{inputData_in_V_read[6:5]}};
        tmp_105_reg_2543 <= {{inputData_in_V_read[4:3]}};
        tmp_110_reg_2548 <= {{inputData_in_V_read[2:1]}};
        tmp_1160_reg_2446 <= tmp_1160_fu_156_p1;
        tmp_1178_reg_2457 <= rem_next_V_5_fu_620_p2[32'd25];
        tmp_1211_reg_2565[11 : 0] <= tmp_1211_fu_1383_p1[11 : 0];
        tmp_1214_reg_2570 <= rem_next_V_11_fu_1396_p2[32'd25];
        tmp_1246_reg_2593[18 : 0] <= tmp_1246_fu_1970_p1[18 : 0];
        tmp_30_reg_2468 <= {{inputData_in_V_read[34:33]}};
        tmp_35_reg_2473 <= {{inputData_in_V_read[32:31]}};
        tmp_40_reg_2478 <= {{inputData_in_V_read[30:29]}};
        tmp_45_reg_2483 <= {{inputData_in_V_read[28:27]}};
        tmp_50_reg_2488 <= {{inputData_in_V_read[26:25]}};
        tmp_55_reg_2493 <= {{inputData_in_V_read[24:23]}};
        tmp_60_reg_2498 <= {{inputData_in_V_read[22:21]}};
        tmp_65_reg_2503 <= {{inputData_in_V_read[20:19]}};
        tmp_70_reg_2508 <= {{inputData_in_V_read[18:17]}};
        tmp_75_reg_2513 <= {{inputData_in_V_read[16:15]}};
        tmp_80_reg_2518 <= {{inputData_in_V_read[14:13]}};
        tmp_85_reg_2523 <= {{inputData_in_V_read[12:11]}};
        tmp_90_reg_2528 <= {{inputData_in_V_read[10:9]}};
        tmp_95_reg_2533 <= {{inputData_in_V_read[8:7]}};
    end
end

assign ap_block_pp0_stage0_flag00000000 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_flag00011001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_return = ((tmp_1274_fu_2422_p3[0:0] === 1'b1) ? tmp_1273_fu_2416_p2 : p_Result_33_19_fu_2430_p3);

assign not_Result_3_fu_182_p2 = (tmp_1161_fu_174_p3 ^ 1'd1);

assign p_0289_2_i_10_fu_1352_p3 = ((tmp_1209_fu_1328_p3[0:0] === 1'b1) ? p_Result_29_10_fu_1286_p5 : rem_next_V_10_fu_1312_p2);

assign p_0289_2_i_11_fu_1409_p3 = ((tmp_1214_fu_1401_p3[0:0] === 1'b1) ? p_Result_29_11_reg_2559 : rem_next_V_11_fu_1396_p2);

assign p_0289_2_i_12_fu_1515_p3 = ((tmp_1219_fu_1491_p3[0:0] === 1'b1) ? p_Result_29_12_reg_2575 : rem_next_V_12_fu_1476_p2);

assign p_0289_2_i_13_fu_1599_p3 = ((tmp_1224_fu_1575_p3[0:0] === 1'b1) ? p_Result_29_13_fu_1533_p5 : rem_next_V_13_fu_1559_p2);

assign p_0289_2_i_14_fu_1684_p3 = ((tmp_1229_fu_1660_p3[0:0] === 1'b1) ? p_Result_29_14_fu_1618_p5 : rem_next_V_14_fu_1644_p2);

assign p_0289_2_i_15_fu_1769_p3 = ((tmp_1234_fu_1745_p3[0:0] === 1'b1) ? p_Result_29_15_fu_1703_p5 : rem_next_V_15_fu_1729_p2);

assign p_0289_2_i_16_fu_1854_p3 = ((tmp_1239_fu_1830_p3[0:0] === 1'b1) ? p_Result_29_16_fu_1788_p5 : rem_next_V_16_fu_1814_p2);

assign p_0289_2_i_17_fu_1939_p3 = ((tmp_1244_fu_1915_p3[0:0] === 1'b1) ? p_Result_29_17_fu_1873_p5 : rem_next_V_17_fu_1899_p2);

assign p_0289_2_i_18_fu_2020_p3 = ((tmp_1249_fu_1996_p3[0:0] === 1'b1) ? p_Result_29_18_reg_2587 : rem_next_V_18_fu_1983_p2);

assign p_0289_2_i_19_fu_2104_p3 = ((tmp_1254_fu_2080_p3[0:0] === 1'b1) ? p_Result_29_19_fu_2038_p5 : rem_next_V_19_fu_2064_p2);

assign p_0289_2_i_1_fu_282_p3 = ((tmp_1163_fu_258_p3[0:0] === 1'b1) ? p_Result_29_1_fu_218_p5 : rem_next_V_1_fu_244_p2);

assign p_0289_2_i_20_fu_2189_p3 = ((tmp_1259_fu_2165_p3[0:0] === 1'b1) ? p_Result_29_20_fu_2123_p5 : rem_next_V_20_fu_2149_p2);

assign p_0289_2_i_21_fu_2274_p3 = ((tmp_1264_fu_2250_p3[0:0] === 1'b1) ? p_Result_29_21_fu_2208_p5 : rem_next_V_21_fu_2234_p2);

assign p_0289_2_i_22_fu_2359_p3 = ((tmp_1269_fu_2335_p3[0:0] === 1'b1) ? p_Result_29_22_fu_2293_p5 : rem_next_V_22_fu_2319_p2);

assign p_0289_2_i_2_fu_376_p3 = ((tmp_1165_fu_352_p3[0:0] === 1'b1) ? p_Result_29_2_fu_312_p5 : rem_next_V_2_fu_338_p2);

assign p_0289_2_i_3_fu_470_p3 = ((tmp_1168_fu_446_p3[0:0] === 1'b1) ? p_Result_29_3_fu_406_p5 : rem_next_V_3_fu_432_p2);

assign p_0289_2_i_4_fu_564_p3 = ((tmp_1172_fu_540_p3[0:0] === 1'b1) ? p_Result_29_4_fu_500_p5 : rem_next_V_4_fu_526_p2);

assign p_0289_2_i_5_fu_634_p3 = ((tmp_1178_fu_626_p3[0:0] === 1'b1) ? p_Result_29_5_fu_594_p5 : rem_next_V_5_fu_620_p2);

assign p_0289_2_i_6_fu_928_p3 = ((tmp_1184_fu_904_p3[0:0] === 1'b1) ? p_Result_29_6_reg_2462 : rem_next_V_6_fu_889_p2);

assign p_0289_2_i_7_fu_1012_p3 = ((tmp_1189_fu_988_p3[0:0] === 1'b1) ? p_Result_29_7_fu_946_p5 : rem_next_V_7_fu_972_p2);

assign p_0289_2_i_8_fu_1097_p3 = ((tmp_1194_fu_1073_p3[0:0] === 1'b1) ? p_Result_29_8_fu_1031_p5 : rem_next_V_8_fu_1057_p2);

assign p_0289_2_i_9_fu_1182_p3 = ((tmp_1199_fu_1158_p3[0:0] === 1'b1) ? p_Result_29_9_fu_1116_p5 : rem_next_V_9_fu_1142_p2);

assign p_0289_2_i_s_fu_1267_p3 = ((tmp_1204_fu_1243_p3[0:0] === 1'b1) ? p_Result_29_s_fu_1201_p5 : rem_next_V_s_fu_1227_p2);

assign p_Result_29_0_rem_s_fu_188_p3 = ((tmp_1161_fu_174_p3[0:0] === 1'b1) ? p_Result_2_fu_160_p3 : rem_next_V_fu_168_p2);

assign p_Result_29_10_fu_1286_p5 = {{p_0289_2_i_s_fu_1267_p3[49:26]}, {tmp_51_fu_1279_p3}};

assign p_Result_29_11_fu_1371_p5 = {{p_0289_2_i_10_fu_1352_p3[49:26]}, {tmp_56_fu_1364_p3}};

assign p_Result_29_12_fu_1427_p5 = {{p_0289_2_i_11_fu_1409_p3[49:26]}, {tmp_61_fu_1420_p3}};

assign p_Result_29_13_fu_1533_p5 = {{p_0289_2_i_12_fu_1515_p3[49:26]}, {tmp_66_fu_1526_p3}};

assign p_Result_29_14_fu_1618_p5 = {{p_0289_2_i_13_fu_1599_p3[49:26]}, {tmp_71_fu_1611_p3}};

assign p_Result_29_15_fu_1703_p5 = {{p_0289_2_i_14_fu_1684_p3[49:26]}, {tmp_76_fu_1696_p3}};

assign p_Result_29_16_fu_1788_p5 = {{p_0289_2_i_15_fu_1769_p3[49:26]}, {tmp_81_fu_1781_p3}};

assign p_Result_29_17_fu_1873_p5 = {{p_0289_2_i_16_fu_1854_p3[49:26]}, {tmp_86_fu_1866_p3}};

assign p_Result_29_18_fu_1958_p5 = {{p_0289_2_i_17_fu_1939_p3[49:26]}, {tmp_91_fu_1951_p3}};

assign p_Result_29_19_fu_2038_p5 = {{p_0289_2_i_18_fu_2020_p3[49:26]}, {tmp_96_fu_2031_p3}};

assign p_Result_29_1_fu_218_p5 = {{p_Result_29_0_rem_s_fu_188_p3[49:26]}, {tmp_2_fu_210_p3}};

assign p_Result_29_20_fu_2123_p5 = {{p_0289_2_i_19_fu_2104_p3[49:26]}, {tmp_101_fu_2116_p3}};

assign p_Result_29_21_fu_2208_p5 = {{p_0289_2_i_20_fu_2189_p3[49:26]}, {tmp_106_fu_2201_p3}};

assign p_Result_29_22_fu_2293_p5 = {{p_0289_2_i_21_fu_2274_p3[49:26]}, {tmp_111_fu_2286_p3}};

assign p_Result_29_23_fu_2380_p5 = {{p_0289_2_i_22_fu_2359_p3[49:26]}, {tmp_115_fu_2371_p4}};

assign p_Result_29_2_fu_312_p5 = {{p_0289_2_i_1_fu_282_p3[49:26]}, {tmp_8_fu_304_p3}};

assign p_Result_29_3_fu_406_p5 = {{p_0289_2_i_2_fu_376_p3[49:26]}, {tmp_11_fu_398_p3}};

assign p_Result_29_4_fu_500_p5 = {{p_0289_2_i_3_fu_470_p3[49:26]}, {tmp_16_fu_492_p3}};

assign p_Result_29_5_fu_594_p5 = {{p_0289_2_i_4_fu_564_p3[49:26]}, {tmp_21_fu_586_p3}};

assign p_Result_29_6_fu_664_p5 = {{p_0289_2_i_5_fu_634_p3[49:26]}, {tmp_26_fu_656_p3}};

assign p_Result_29_7_fu_946_p5 = {{p_0289_2_i_6_fu_928_p3[49:26]}, {tmp_31_fu_939_p3}};

assign p_Result_29_8_fu_1031_p5 = {{p_0289_2_i_7_fu_1012_p3[49:26]}, {tmp_36_fu_1024_p3}};

assign p_Result_29_9_fu_1116_p5 = {{p_0289_2_i_8_fu_1097_p3[49:26]}, {tmp_41_fu_1109_p3}};

assign p_Result_29_s_fu_1201_p5 = {{p_0289_2_i_9_fu_1182_p3[49:26]}, {tmp_46_fu_1194_p3}};

assign p_Result_2_fu_160_p3 = {{49'd0}, {tmp_fu_148_p3}};

assign p_Result_30_10_s_fu_1217_p4 = {{{{25'd0}, {tmp_1201_fu_1213_p1}}}, {2'd1}};

assign p_Result_30_11_s_fu_1302_p4 = {{{{25'd0}, {tmp_1206_fu_1298_p1}}}, {2'd1}};

assign p_Result_30_12_s_fu_1387_p4 = {{{{25'd0}, {tmp_1211_reg_2565}}}, {2'd1}};

assign p_Result_30_13_s_fu_1466_p4 = {{{{25'd0}, {tmp_1216_fu_1462_p1}}}, {2'd1}};

assign p_Result_30_14_s_fu_1549_p4 = {{{{25'd0}, {tmp_1221_fu_1545_p1}}}, {2'd1}};

assign p_Result_30_15_s_fu_1634_p4 = {{{{25'd0}, {tmp_1226_fu_1630_p1}}}, {2'd1}};

assign p_Result_30_16_s_fu_1719_p4 = {{{{25'd0}, {tmp_1231_fu_1715_p1}}}, {2'd1}};

assign p_Result_30_17_s_fu_1804_p4 = {{{{25'd0}, {tmp_1236_fu_1800_p1}}}, {2'd1}};

assign p_Result_30_18_s_fu_1889_p4 = {{{{25'd0}, {tmp_1241_fu_1885_p1}}}, {2'd1}};

assign p_Result_30_19_s_fu_1974_p4 = {{{{25'd0}, {tmp_1246_reg_2593}}}, {2'd1}};

assign p_Result_30_1_s_fu_234_p4 = {{{{25'd0}, {tmp_3_fu_230_p1}}}, {2'd1}};

assign p_Result_30_20_s_fu_2054_p4 = {{{{25'd0}, {tmp_1251_fu_2050_p1}}}, {2'd1}};

assign p_Result_30_21_s_fu_2139_p4 = {{{{25'd0}, {tmp_1256_fu_2135_p1}}}, {2'd1}};

assign p_Result_30_22_s_fu_2224_p4 = {{{{25'd0}, {tmp_1261_fu_2220_p1}}}, {2'd1}};

assign p_Result_30_23_s_fu_2309_p4 = {{{{25'd0}, {tmp_1266_fu_2305_p1}}}, {2'd1}};

assign p_Result_30_24_s_fu_2396_p4 = {{{{25'd0}, {tmp_1271_fu_2392_p1}}}, {2'd1}};

assign p_Result_30_2_s_fu_328_p4 = {{{{25'd0}, {tmp_9_fu_324_p1}}}, {2'd1}};

assign p_Result_30_3_s_fu_422_p4 = {{{{25'd0}, {tmp_12_fu_418_p1}}}, {2'd1}};

assign p_Result_30_4_s_fu_516_p4 = {{{{25'd0}, {tmp_17_fu_512_p1}}}, {2'd1}};

assign p_Result_30_5_s_fu_610_p4 = {{{{25'd0}, {tmp_1175_fu_606_p1}}}, {2'd1}};

assign p_Result_30_6_s_fu_879_p4 = {{{{25'd0}, {tmp_1181_fu_875_p1}}}, {2'd1}};

assign p_Result_30_7_s_fu_962_p4 = {{{{25'd0}, {tmp_1186_fu_958_p1}}}, {2'd1}};

assign p_Result_30_8_s_fu_1047_p4 = {{{{25'd0}, {tmp_1191_fu_1043_p1}}}, {2'd1}};

assign p_Result_30_9_s_fu_1132_p4 = {{{{25'd0}, {tmp_1196_fu_1128_p1}}}, {2'd1}};

assign p_Result_33_10_fu_1668_p3 = {{tmp_1227_fu_1650_p1}, {1'd1}};

assign p_Result_33_11_fu_1753_p3 = {{tmp_1232_fu_1735_p1}, {1'd1}};

assign p_Result_33_12_fu_1838_p3 = {{tmp_1237_fu_1820_p1}, {1'd1}};

assign p_Result_33_13_fu_1923_p3 = {{tmp_1242_fu_1905_p1}, {1'd1}};

assign p_Result_33_14_fu_2004_p3 = {{tmp_1247_fu_1988_p1}, {1'd1}};

assign p_Result_33_15_fu_2088_p3 = {{tmp_1252_fu_2070_p1}, {1'd1}};

assign p_Result_33_16_fu_2173_p3 = {{tmp_1257_fu_2155_p1}, {1'd1}};

assign p_Result_33_17_fu_2258_p3 = {{tmp_1262_fu_2240_p1}, {1'd1}};

assign p_Result_33_18_fu_2343_p3 = {{tmp_1267_fu_2325_p1}, {1'd1}};

assign p_Result_33_19_fu_2430_p3 = {{tmp_1272_fu_2412_p1}, {1'd1}};

assign p_Result_33_1_fu_1336_p3 = {{tmp_1207_fu_1318_p1}, {1'd1}};

assign p_Result_33_2_fu_1447_p3 = {{tmp_1212_fu_1439_p1}, {1'd1}};

assign p_Result_33_3_fu_1499_p3 = {{tmp_1217_fu_1481_p1}, {1'd1}};

assign p_Result_33_4_fu_1583_p3 = {{tmp_1222_fu_1565_p1}, {1'd1}};

assign p_Result_33_5_fu_864_p1 = tmp_1179_fu_857_p3;

assign p_Result_33_6_fu_912_p3 = {{tmp_1182_fu_894_p1}, {1'd1}};

assign p_Result_33_7_fu_996_p3 = {{tmp_1187_fu_978_p1}, {1'd1}};

assign p_Result_33_8_fu_1081_p3 = {{tmp_1192_fu_1063_p1}, {1'd1}};

assign p_Result_33_9_fu_1166_p3 = {{tmp_1197_fu_1148_p1}, {1'd1}};

assign p_Result_33_s_fu_1251_p3 = {{tmp_1202_fu_1233_p1}, {1'd1}};

assign rem_next_V_10_fu_1312_p2 = (p_Result_29_10_fu_1286_p5 - p_Result_30_11_s_fu_1302_p4);

assign rem_next_V_11_fu_1396_p2 = (p_Result_29_11_reg_2559 - p_Result_30_12_s_fu_1387_p4);

assign rem_next_V_12_fu_1476_p2 = (p_Result_29_12_reg_2575 - p_Result_30_13_s_fu_1466_p4);

assign rem_next_V_13_fu_1559_p2 = (p_Result_29_13_fu_1533_p5 - p_Result_30_14_s_fu_1549_p4);

assign rem_next_V_14_fu_1644_p2 = (p_Result_29_14_fu_1618_p5 - p_Result_30_15_s_fu_1634_p4);

assign rem_next_V_15_fu_1729_p2 = (p_Result_29_15_fu_1703_p5 - p_Result_30_16_s_fu_1719_p4);

assign rem_next_V_16_fu_1814_p2 = (p_Result_29_16_fu_1788_p5 - p_Result_30_17_s_fu_1804_p4);

assign rem_next_V_17_fu_1899_p2 = (p_Result_29_17_fu_1873_p5 - p_Result_30_18_s_fu_1889_p4);

assign rem_next_V_18_fu_1983_p2 = (p_Result_29_18_reg_2587 - p_Result_30_19_s_fu_1974_p4);

assign rem_next_V_19_fu_2064_p2 = (p_Result_29_19_fu_2038_p5 - p_Result_30_20_s_fu_2054_p4);

assign rem_next_V_1_fu_244_p2 = (p_Result_29_1_fu_218_p5 - p_Result_30_1_s_fu_234_p4);

assign rem_next_V_20_fu_2149_p2 = (p_Result_29_20_fu_2123_p5 - p_Result_30_21_s_fu_2139_p4);

assign rem_next_V_21_fu_2234_p2 = (p_Result_29_21_fu_2208_p5 - p_Result_30_22_s_fu_2224_p4);

assign rem_next_V_22_fu_2319_p2 = (p_Result_29_22_fu_2293_p5 - p_Result_30_23_s_fu_2309_p4);

assign rem_next_V_23_fu_2406_p2 = (p_Result_29_23_fu_2380_p5 - p_Result_30_24_s_fu_2396_p4);

assign rem_next_V_2_fu_338_p2 = (p_Result_29_2_fu_312_p5 - p_Result_30_2_s_fu_328_p4);

assign rem_next_V_3_fu_432_p2 = (p_Result_29_3_fu_406_p5 - p_Result_30_3_s_fu_422_p4);

assign rem_next_V_4_fu_526_p2 = (p_Result_29_4_fu_500_p5 - p_Result_30_4_s_fu_516_p4);

assign rem_next_V_5_fu_620_p2 = (p_Result_29_5_fu_594_p5 - p_Result_30_5_s_fu_610_p4);

assign rem_next_V_6_fu_889_p2 = (p_Result_29_6_reg_2462 - p_Result_30_6_s_fu_879_p4);

assign rem_next_V_7_fu_972_p2 = (p_Result_29_7_fu_946_p5 - p_Result_30_7_s_fu_962_p4);

assign rem_next_V_8_fu_1057_p2 = (p_Result_29_8_fu_1031_p5 - p_Result_30_8_s_fu_1047_p4);

assign rem_next_V_9_fu_1142_p2 = (p_Result_29_9_fu_1116_p5 - p_Result_30_9_s_fu_1132_p4);

assign rem_next_V_fu_168_p2 = ($signed(50'd1125899906842623) + $signed(p_Result_2_fu_160_p3));

assign rem_next_V_s_fu_1227_p2 = (p_Result_29_s_fu_1201_p5 - p_Result_30_10_s_fu_1217_p4);

assign sqrt_int_2_10_fu_1676_p3 = ((tmp_1229_fu_1660_p3[0:0] === 1'b1) ? tmp_1228_fu_1654_p2 : p_Result_33_10_fu_1668_p3);

assign sqrt_int_2_11_fu_1761_p3 = ((tmp_1234_fu_1745_p3[0:0] === 1'b1) ? tmp_1233_fu_1739_p2 : p_Result_33_11_fu_1753_p3);

assign sqrt_int_2_12_fu_1846_p3 = ((tmp_1239_fu_1830_p3[0:0] === 1'b1) ? tmp_1238_fu_1824_p2 : p_Result_33_12_fu_1838_p3);

assign sqrt_int_2_13_fu_1931_p3 = ((tmp_1244_fu_1915_p3[0:0] === 1'b1) ? tmp_1243_fu_1909_p2 : p_Result_33_13_fu_1923_p3);

assign sqrt_int_2_14_fu_2012_p3 = ((tmp_1249_fu_1996_p3[0:0] === 1'b1) ? tmp_1248_fu_1991_p2 : p_Result_33_14_fu_2004_p3);

assign sqrt_int_2_15_fu_2096_p3 = ((tmp_1254_fu_2080_p3[0:0] === 1'b1) ? tmp_1253_fu_2074_p2 : p_Result_33_15_fu_2088_p3);

assign sqrt_int_2_16_fu_2181_p3 = ((tmp_1259_fu_2165_p3[0:0] === 1'b1) ? tmp_1258_fu_2159_p2 : p_Result_33_16_fu_2173_p3);

assign sqrt_int_2_17_fu_2266_p3 = ((tmp_1264_fu_2250_p3[0:0] === 1'b1) ? tmp_1263_fu_2244_p2 : p_Result_33_17_fu_2258_p3);

assign sqrt_int_2_18_fu_2351_p3 = ((tmp_1269_fu_2335_p3[0:0] === 1'b1) ? tmp_1268_fu_2329_p2 : p_Result_33_18_fu_2343_p3);

assign sqrt_int_2_1_fu_1344_p3 = ((tmp_1209_fu_1328_p3[0:0] === 1'b1) ? tmp_1208_fu_1322_p2 : p_Result_33_1_fu_1336_p3);

assign sqrt_int_2_1_v_fu_274_p3 = ((tmp_1163_fu_258_p3[0:0] === 1'b1) ? tmp_4_fu_250_p3 : tmp_118_fu_266_p3);

assign sqrt_int_2_2_fu_1455_p3 = ((tmp_1214_reg_2570[0:0] === 1'b1) ? tmp_1213_fu_1442_p2 : p_Result_33_2_fu_1447_p3);

assign sqrt_int_2_2_v_fu_368_p3 = ((tmp_1165_fu_352_p3[0:0] === 1'b1) ? tmp_s_fu_344_p3 : tmp_584_fu_360_p3);

assign sqrt_int_2_3_fu_1507_p3 = ((tmp_1219_fu_1491_p3[0:0] === 1'b1) ? tmp_1218_fu_1485_p2 : p_Result_33_3_fu_1499_p3);

assign sqrt_int_2_3_v_fu_462_p3 = ((tmp_1168_fu_446_p3[0:0] === 1'b1) ? tmp_1167_fu_438_p3 : tmp_1169_fu_454_p3);

assign sqrt_int_2_4_fu_1591_p3 = ((tmp_1224_fu_1575_p3[0:0] === 1'b1) ? tmp_1223_fu_1569_p2 : p_Result_33_4_fu_1583_p3);

assign sqrt_int_2_4_v_fu_556_p3 = ((tmp_1172_fu_540_p3[0:0] === 1'b1) ? tmp_1171_fu_532_p3 : tmp_1173_fu_548_p3);

assign sqrt_int_2_5_fu_868_p3 = ((tmp_1178_reg_2457[0:0] === 1'b1) ? tmp_1177_fu_853_p1 : p_Result_33_5_fu_864_p1);

assign sqrt_int_2_6_fu_920_p3 = ((tmp_1184_fu_904_p3[0:0] === 1'b1) ? tmp_1183_fu_898_p2 : p_Result_33_6_fu_912_p3);

assign sqrt_int_2_7_fu_1004_p3 = ((tmp_1189_fu_988_p3[0:0] === 1'b1) ? tmp_1188_fu_982_p2 : p_Result_33_7_fu_996_p3);

assign sqrt_int_2_8_fu_1089_p3 = ((tmp_1194_fu_1073_p3[0:0] === 1'b1) ? tmp_1193_fu_1067_p2 : p_Result_33_8_fu_1081_p3);

assign sqrt_int_2_9_fu_1174_p3 = ((tmp_1199_fu_1158_p3[0:0] === 1'b1) ? tmp_1198_fu_1152_p2 : p_Result_33_9_fu_1166_p3);

assign sqrt_int_2_s_fu_1259_p3 = ((tmp_1204_fu_1243_p3[0:0] === 1'b1) ? tmp_1203_fu_1237_p2 : p_Result_33_s_fu_1251_p3);

assign tmp_101_fu_2116_p3 = {{tmp_1255_fu_2112_p1}, {ap_reg_pp0_iter3_tmp_100_reg_2538}};

assign tmp_106_fu_2201_p3 = {{tmp_1260_fu_2197_p1}, {ap_reg_pp0_iter3_tmp_105_reg_2543}};

assign tmp_10_fu_388_p4 = {{inputData_in_V_read[42:41]}};

assign tmp_111_fu_2286_p3 = {{tmp_1265_fu_2282_p1}, {ap_reg_pp0_iter3_tmp_110_reg_2548}};

assign tmp_115_fu_2371_p4 = {{{tmp_1270_fu_2367_p1}, {ap_reg_pp0_iter3_tmp_1160_reg_2446}}, {1'd0}};

assign tmp_1160_fu_156_p1 = inputData_in_V_read[0:0];

assign tmp_1161_fu_174_p3 = rem_next_V_fu_168_p2[32'd25];

assign tmp_1162_fu_196_p1 = p_Result_29_0_rem_s_fu_188_p3[23:0];

assign tmp_1163_fu_258_p3 = rem_next_V_1_fu_244_p2[32'd25];

assign tmp_1164_fu_290_p1 = p_0289_2_i_1_fu_282_p3[23:0];

assign tmp_1165_fu_352_p3 = rem_next_V_2_fu_338_p2[32'd25];

assign tmp_1166_fu_384_p1 = p_0289_2_i_2_fu_376_p3[23:0];

assign tmp_1167_fu_438_p3 = {{sqrt_int_2_2_v_fu_368_p3}, {1'd0}};

assign tmp_1168_fu_446_p3 = rem_next_V_3_fu_432_p2[32'd25];

assign tmp_1169_fu_454_p3 = {{sqrt_int_2_2_v_fu_368_p3}, {1'd1}};

assign tmp_1170_fu_478_p1 = p_0289_2_i_3_fu_470_p3[23:0];

assign tmp_1171_fu_532_p3 = {{sqrt_int_2_3_v_fu_462_p3}, {1'd0}};

assign tmp_1172_fu_540_p3 = rem_next_V_4_fu_526_p2[32'd25];

assign tmp_1173_fu_548_p3 = {{sqrt_int_2_3_v_fu_462_p3}, {1'd1}};

assign tmp_1174_fu_572_p1 = p_0289_2_i_4_fu_564_p3[23:0];

assign tmp_1175_fu_606_p1 = sqrt_int_2_4_v_fu_556_p3;

assign tmp_1176_fu_846_p3 = {{sqrt_int_2_4_v_reg_2451}, {1'd0}};

assign tmp_1177_fu_853_p1 = tmp_1176_fu_846_p3;

assign tmp_1178_fu_626_p3 = rem_next_V_5_fu_620_p2[32'd25];

assign tmp_1179_fu_857_p3 = {{sqrt_int_2_4_v_reg_2451}, {1'd1}};

assign tmp_1180_fu_642_p1 = p_0289_2_i_5_fu_634_p3[23:0];

assign tmp_1181_fu_875_p1 = sqrt_int_2_5_fu_868_p3[22:0];

assign tmp_1182_fu_894_p1 = sqrt_int_2_5_fu_868_p3[23:0];

assign tmp_1183_fu_898_p2 = sqrt_int_2_5_fu_868_p3 << 25'd1;

assign tmp_1184_fu_904_p3 = rem_next_V_6_fu_889_p2[32'd25];

assign tmp_1185_fu_935_p1 = p_0289_2_i_6_fu_928_p3[23:0];

assign tmp_1186_fu_958_p1 = sqrt_int_2_6_fu_920_p3[22:0];

assign tmp_1187_fu_978_p1 = sqrt_int_2_6_fu_920_p3[23:0];

assign tmp_1188_fu_982_p2 = sqrt_int_2_6_fu_920_p3 << 25'd1;

assign tmp_1189_fu_988_p3 = rem_next_V_7_fu_972_p2[32'd25];

assign tmp_118_fu_266_p3 = {{not_Result_3_fu_182_p2}, {1'd1}};

assign tmp_1190_fu_1020_p1 = p_0289_2_i_7_fu_1012_p3[23:0];

assign tmp_1191_fu_1043_p1 = sqrt_int_2_7_fu_1004_p3[22:0];

assign tmp_1192_fu_1063_p1 = sqrt_int_2_7_fu_1004_p3[23:0];

assign tmp_1193_fu_1067_p2 = sqrt_int_2_7_fu_1004_p3 << 25'd1;

assign tmp_1194_fu_1073_p3 = rem_next_V_8_fu_1057_p2[32'd25];

assign tmp_1195_fu_1105_p1 = p_0289_2_i_8_fu_1097_p3[23:0];

assign tmp_1196_fu_1128_p1 = sqrt_int_2_8_fu_1089_p3[22:0];

assign tmp_1197_fu_1148_p1 = sqrt_int_2_8_fu_1089_p3[23:0];

assign tmp_1198_fu_1152_p2 = sqrt_int_2_8_fu_1089_p3 << 25'd1;

assign tmp_1199_fu_1158_p3 = rem_next_V_9_fu_1142_p2[32'd25];

assign tmp_11_fu_398_p3 = {{tmp_1166_fu_384_p1}, {tmp_10_fu_388_p4}};

assign tmp_1200_fu_1190_p1 = p_0289_2_i_9_fu_1182_p3[23:0];

assign tmp_1201_fu_1213_p1 = sqrt_int_2_9_fu_1174_p3[22:0];

assign tmp_1202_fu_1233_p1 = sqrt_int_2_9_fu_1174_p3[23:0];

assign tmp_1203_fu_1237_p2 = sqrt_int_2_9_fu_1174_p3 << 25'd1;

assign tmp_1204_fu_1243_p3 = rem_next_V_s_fu_1227_p2[32'd25];

assign tmp_1205_fu_1275_p1 = p_0289_2_i_s_fu_1267_p3[23:0];

assign tmp_1206_fu_1298_p1 = sqrt_int_2_s_fu_1259_p3[22:0];

assign tmp_1207_fu_1318_p1 = sqrt_int_2_s_fu_1259_p3[23:0];

assign tmp_1208_fu_1322_p2 = sqrt_int_2_s_fu_1259_p3 << 25'd1;

assign tmp_1209_fu_1328_p3 = rem_next_V_10_fu_1312_p2[32'd25];

assign tmp_1210_fu_1360_p1 = p_0289_2_i_10_fu_1352_p3[23:0];

assign tmp_1211_fu_1383_p1 = sqrt_int_2_1_fu_1344_p3[22:0];

assign tmp_1212_fu_1439_p1 = ap_reg_pp0_iter2_sqrt_int_2_1_reg_2553[23:0];

assign tmp_1213_fu_1442_p2 = ap_reg_pp0_iter2_sqrt_int_2_1_reg_2553 << 25'd1;

assign tmp_1214_fu_1401_p3 = rem_next_V_11_fu_1396_p2[32'd25];

assign tmp_1215_fu_1416_p1 = p_0289_2_i_11_fu_1409_p3[23:0];

assign tmp_1216_fu_1462_p1 = sqrt_int_2_2_fu_1455_p3[22:0];

assign tmp_1217_fu_1481_p1 = sqrt_int_2_2_fu_1455_p3[23:0];

assign tmp_1218_fu_1485_p2 = sqrt_int_2_2_fu_1455_p3 << 25'd1;

assign tmp_1219_fu_1491_p3 = rem_next_V_12_fu_1476_p2[32'd25];

assign tmp_1220_fu_1522_p1 = p_0289_2_i_12_fu_1515_p3[23:0];

assign tmp_1221_fu_1545_p1 = sqrt_int_2_3_fu_1507_p3[22:0];

assign tmp_1222_fu_1565_p1 = sqrt_int_2_3_fu_1507_p3[23:0];

assign tmp_1223_fu_1569_p2 = sqrt_int_2_3_fu_1507_p3 << 25'd1;

assign tmp_1224_fu_1575_p3 = rem_next_V_13_fu_1559_p2[32'd25];

assign tmp_1225_fu_1607_p1 = p_0289_2_i_13_fu_1599_p3[23:0];

assign tmp_1226_fu_1630_p1 = sqrt_int_2_4_fu_1591_p3[22:0];

assign tmp_1227_fu_1650_p1 = sqrt_int_2_4_fu_1591_p3[23:0];

assign tmp_1228_fu_1654_p2 = sqrt_int_2_4_fu_1591_p3 << 25'd1;

assign tmp_1229_fu_1660_p3 = rem_next_V_14_fu_1644_p2[32'd25];

assign tmp_1230_fu_1692_p1 = p_0289_2_i_14_fu_1684_p3[23:0];

assign tmp_1231_fu_1715_p1 = sqrt_int_2_10_fu_1676_p3[22:0];

assign tmp_1232_fu_1735_p1 = sqrt_int_2_10_fu_1676_p3[23:0];

assign tmp_1233_fu_1739_p2 = sqrt_int_2_10_fu_1676_p3 << 25'd1;

assign tmp_1234_fu_1745_p3 = rem_next_V_15_fu_1729_p2[32'd25];

assign tmp_1235_fu_1777_p1 = p_0289_2_i_15_fu_1769_p3[23:0];

assign tmp_1236_fu_1800_p1 = sqrt_int_2_11_fu_1761_p3[22:0];

assign tmp_1237_fu_1820_p1 = sqrt_int_2_11_fu_1761_p3[23:0];

assign tmp_1238_fu_1824_p2 = sqrt_int_2_11_fu_1761_p3 << 25'd1;

assign tmp_1239_fu_1830_p3 = rem_next_V_16_fu_1814_p2[32'd25];

assign tmp_1240_fu_1862_p1 = p_0289_2_i_16_fu_1854_p3[23:0];

assign tmp_1241_fu_1885_p1 = sqrt_int_2_12_fu_1846_p3[22:0];

assign tmp_1242_fu_1905_p1 = sqrt_int_2_12_fu_1846_p3[23:0];

assign tmp_1243_fu_1909_p2 = sqrt_int_2_12_fu_1846_p3 << 25'd1;

assign tmp_1244_fu_1915_p3 = rem_next_V_17_fu_1899_p2[32'd25];

assign tmp_1245_fu_1947_p1 = p_0289_2_i_17_fu_1939_p3[23:0];

assign tmp_1246_fu_1970_p1 = sqrt_int_2_13_fu_1931_p3[22:0];

assign tmp_1247_fu_1988_p1 = sqrt_int_2_13_reg_2581[23:0];

assign tmp_1248_fu_1991_p2 = sqrt_int_2_13_reg_2581 << 25'd1;

assign tmp_1249_fu_1996_p3 = rem_next_V_18_fu_1983_p2[32'd25];

assign tmp_1250_fu_2027_p1 = p_0289_2_i_18_fu_2020_p3[23:0];

assign tmp_1251_fu_2050_p1 = sqrt_int_2_14_fu_2012_p3[22:0];

assign tmp_1252_fu_2070_p1 = sqrt_int_2_14_fu_2012_p3[23:0];

assign tmp_1253_fu_2074_p2 = sqrt_int_2_14_fu_2012_p3 << 25'd1;

assign tmp_1254_fu_2080_p3 = rem_next_V_19_fu_2064_p2[32'd25];

assign tmp_1255_fu_2112_p1 = p_0289_2_i_19_fu_2104_p3[23:0];

assign tmp_1256_fu_2135_p1 = sqrt_int_2_15_fu_2096_p3[22:0];

assign tmp_1257_fu_2155_p1 = sqrt_int_2_15_fu_2096_p3[23:0];

assign tmp_1258_fu_2159_p2 = sqrt_int_2_15_fu_2096_p3 << 25'd1;

assign tmp_1259_fu_2165_p3 = rem_next_V_20_fu_2149_p2[32'd25];

assign tmp_1260_fu_2197_p1 = p_0289_2_i_20_fu_2189_p3[23:0];

assign tmp_1261_fu_2220_p1 = sqrt_int_2_16_fu_2181_p3[22:0];

assign tmp_1262_fu_2240_p1 = sqrt_int_2_16_fu_2181_p3[23:0];

assign tmp_1263_fu_2244_p2 = sqrt_int_2_16_fu_2181_p3 << 25'd1;

assign tmp_1264_fu_2250_p3 = rem_next_V_21_fu_2234_p2[32'd25];

assign tmp_1265_fu_2282_p1 = p_0289_2_i_21_fu_2274_p3[23:0];

assign tmp_1266_fu_2305_p1 = sqrt_int_2_17_fu_2266_p3[22:0];

assign tmp_1267_fu_2325_p1 = sqrt_int_2_17_fu_2266_p3[23:0];

assign tmp_1268_fu_2329_p2 = sqrt_int_2_17_fu_2266_p3 << 25'd1;

assign tmp_1269_fu_2335_p3 = rem_next_V_22_fu_2319_p2[32'd25];

assign tmp_1270_fu_2367_p1 = p_0289_2_i_22_fu_2359_p3[23:0];

assign tmp_1271_fu_2392_p1 = sqrt_int_2_18_fu_2351_p3[22:0];

assign tmp_1272_fu_2412_p1 = sqrt_int_2_18_fu_2351_p3[23:0];

assign tmp_1273_fu_2416_p2 = sqrt_int_2_18_fu_2351_p3 << 25'd1;

assign tmp_1274_fu_2422_p3 = rem_next_V_23_fu_2406_p2[32'd25];

assign tmp_12_fu_418_p1 = sqrt_int_2_2_v_fu_368_p3;

assign tmp_15_fu_482_p4 = {{inputData_in_V_read[40:39]}};

assign tmp_16_fu_492_p3 = {{tmp_1170_fu_478_p1}, {tmp_15_fu_482_p4}};

assign tmp_17_fu_512_p1 = sqrt_int_2_3_v_fu_462_p3;

assign tmp_1_fu_200_p4 = {{inputData_in_V_read[46:45]}};

assign tmp_20_fu_576_p4 = {{inputData_in_V_read[38:37]}};

assign tmp_21_fu_586_p3 = {{tmp_1174_fu_572_p1}, {tmp_20_fu_576_p4}};

assign tmp_25_fu_646_p4 = {{inputData_in_V_read[36:35]}};

assign tmp_26_fu_656_p3 = {{tmp_1180_fu_642_p1}, {tmp_25_fu_646_p4}};

assign tmp_2_fu_210_p3 = {{tmp_1162_fu_196_p1}, {tmp_1_fu_200_p4}};

assign tmp_31_fu_939_p3 = {{tmp_1185_fu_935_p1}, {tmp_30_reg_2468}};

assign tmp_36_fu_1024_p3 = {{tmp_1190_fu_1020_p1}, {tmp_35_reg_2473}};

assign tmp_3_fu_230_p1 = not_Result_3_fu_182_p2;

assign tmp_41_fu_1109_p3 = {{tmp_1195_fu_1105_p1}, {tmp_40_reg_2478}};

assign tmp_46_fu_1194_p3 = {{tmp_1200_fu_1190_p1}, {tmp_45_reg_2483}};

assign tmp_4_fu_250_p3 = {{not_Result_3_fu_182_p2}, {1'd0}};

assign tmp_51_fu_1279_p3 = {{tmp_1205_fu_1275_p1}, {tmp_50_reg_2488}};

assign tmp_56_fu_1364_p3 = {{tmp_1210_fu_1360_p1}, {tmp_55_reg_2493}};

assign tmp_584_fu_360_p3 = {{sqrt_int_2_1_v_fu_274_p3}, {1'd1}};

assign tmp_61_fu_1420_p3 = {{tmp_1215_fu_1416_p1}, {ap_reg_pp0_iter1_tmp_60_reg_2498}};

assign tmp_66_fu_1526_p3 = {{tmp_1220_fu_1522_p1}, {ap_reg_pp0_iter2_tmp_65_reg_2503}};

assign tmp_71_fu_1611_p3 = {{tmp_1225_fu_1607_p1}, {ap_reg_pp0_iter2_tmp_70_reg_2508}};

assign tmp_76_fu_1696_p3 = {{tmp_1230_fu_1692_p1}, {ap_reg_pp0_iter2_tmp_75_reg_2513}};

assign tmp_7_fu_294_p4 = {{inputData_in_V_read[44:43]}};

assign tmp_81_fu_1781_p3 = {{tmp_1235_fu_1777_p1}, {ap_reg_pp0_iter2_tmp_80_reg_2518}};

assign tmp_86_fu_1866_p3 = {{tmp_1240_fu_1862_p1}, {ap_reg_pp0_iter2_tmp_85_reg_2523}};

assign tmp_8_fu_304_p3 = {{tmp_1164_fu_290_p1}, {tmp_7_fu_294_p4}};

assign tmp_91_fu_1951_p3 = {{tmp_1245_fu_1947_p1}, {ap_reg_pp0_iter2_tmp_90_reg_2528}};

assign tmp_96_fu_2031_p3 = {{tmp_1250_fu_2027_p1}, {ap_reg_pp0_iter3_tmp_95_reg_2533}};

assign tmp_9_fu_324_p1 = sqrt_int_2_1_v_fu_274_p3;

assign tmp_fu_148_p3 = inputData_in_V_read[32'd47];

assign tmp_s_fu_344_p3 = {{sqrt_int_2_1_v_fu_274_p3}, {1'd0}};

always @ (posedge ap_clk) begin
    sqrt_int_2_1_reg_2553[24:12] <= 13'b0000000000000;
    ap_reg_pp0_iter2_sqrt_int_2_1_reg_2553[24:12] <= 13'b0000000000000;
    tmp_1211_reg_2565[22:12] <= 11'b00000000000;
    sqrt_int_2_13_reg_2581[24:19] <= 6'b000000;
    tmp_1246_reg_2593[22:19] <= 4'b0000;
end

endmodule //cordic_base
